In [3]:
import pandas as pd
import string as str

In [4]:
#loading dimentional data
dim_city = pd.read_csv("H:\Files & Docs\Academics\Courses\Data Analytics\CodeBasics\Power BI\Portfolio\BigQuery\Goodcabs BI Analysis\Datasets\csv_files\dim_city.csv")
dim_date = pd.read_csv("H:\Files & Docs\Academics\Courses\Data Analytics\CodeBasics\Power BI\Portfolio\BigQuery\Goodcabs BI Analysis\Datasets\csv_files\dim_date.csv")
dim_repeat_trip_distribution = pd.read_csv("H:\Files & Docs\Academics\Courses\Data Analytics\CodeBasics\Power BI\Portfolio\BigQuery\Goodcabs BI Analysis\Datasets\csv_files\dim_repeat_trip_distribution.csv")

#loading fact data
fact_passenger_summary = pd.read_csv(r"H:\Files & Docs\Academics\Courses\Data Analytics\CodeBasics\Power BI\Portfolio\BigQuery\Goodcabs BI Analysis\Datasets\csv_files\fact_passenger_summary.csv")
fact_trips = pd.read_csv(r"H:\Files & Docs\Academics\Courses\Data Analytics\CodeBasics\Power BI\Portfolio\BigQuery\Goodcabs BI Analysis\Datasets\csv_files\fact_trips.csv")

#loading target data
city_target_passenger_rating = pd.read_csv("H:\Files & Docs\Academics\Courses\Data Analytics\CodeBasics\Power BI\Portfolio\BigQuery\Goodcabs BI Analysis\Datasets\csv_files\city_target_passenger_rating.csv")
monthly_target_new_passengers = pd.read_csv("H:\Files & Docs\Academics\Courses\Data Analytics\CodeBasics\Power BI\Portfolio\BigQuery\Goodcabs BI Analysis\Datasets\csv_files\monthly_target_new_passengers.csv")
monthly_target_trips = pd.read_csv("H:\Files & Docs\Academics\Courses\Data Analytics\CodeBasics\Power BI\Portfolio\BigQuery\Goodcabs BI Analysis\Datasets\csv_files\monthly_target_trips.csv")

In [5]:
dim_city

  city_id      city_name
0    RJ01         Jaipur
1    UP01        Lucknow
2    GJ01          Surat
3    KL01          Kochi
4    MP01         Indore
5    CH01     Chandigarh
6    GJ02       Vadodara
7    AP01  Visakhapatnam
8    TN01     Coimbatore
9    KA01         Mysore

In [6]:
dim_date.head()

         date start_of_month month_name day_type
0  2024-01-01     2024-01-01    January  Weekday
1  2024-01-02     2024-01-01    January  Weekday
2  2024-01-03     2024-01-01    January  Weekday
3  2024-01-04     2024-01-01    January  Weekday
4  2024-01-05     2024-01-01    January  Weekday

In [7]:
dim_repeat_trip_distribution.head()

        month city_id trip_count  repeat_passenger_count
0  2024-01-01    AP01   10-Trips                       7
1  2024-01-01    AP01    2-Trips                     352
2  2024-01-01    AP01    3-Trips                     158
3  2024-01-01    AP01    4-Trips                      53
4  2024-01-01    AP01    5-Trips                      38

In [8]:
fact_passenger_summary.head()

        month city_id  new_passengers  repeat_passengers  total_passengers
0  2024-01-01    AP01            2513                650              3163
1  2024-01-01    CH01            3920                720              4640
2  2024-01-01    GJ01            2432               1184              3616
3  2024-01-01    GJ02            2089                544              2633
4  2024-01-01    KA01            1957                172              2129

In [9]:
fact_trips.head()

,trip_id,date,city_id,passenger_type,distance_travelled(km),fare_amount,passenger_rating,driver_rating
0,TRPLUC240113d55de2fb,2024-01-13,UP01,repeated,11,158,5,5
1,TRPVAD240129a3b6dba8,2024-01-29,GJ02,repeated,7,74,5,5
2,TRPCOI240107a42430fb,2024-01-07,TN01,repeated,11,155,8,8
3,TRPKOC240325d7601389,2024-03-25,KL01,repeated,36,427,9,10
4,TRPVIS2406027be97166,2024-06-02,AP01,new,17,265,8,8

In [10]:
city_target_passenger_rating

  city_id  target_avg_passenger_rating
0    CH01                         8.00
1    UP01                         7.25
2    AP01                         8.50
3    MP01                         8.00
4    RJ01                         8.25
5    KA01                         8.50
6    GJ01                         7.00
7    TN01                         8.25
8    KL01                         8.50
9    GJ02                         7.50

In [11]:
monthly_target_new_passengers.head()

        month city_id  target_new_passengers
0  2024-05-01    GJ01                   1500
1  2024-05-01    GJ02                   1500
2  2024-03-01    GJ01                   2000
3  2024-05-01    UP01                   2000
4  2024-05-01    MP01                   2000

In [12]:
monthly_target_trips.head()

        month city_id  total_target_trips
0  2024-03-01    MP01                7000
1  2024-05-01    KA01                2500
2  2024-04-01    UP01               11000
3  2024-02-01    GJ02                6000
4  2024-05-01    KL01                9000

In [13]:
dim_date.info() #date and start_of_the_month column are listed as object type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 182 entries, 0 to 181
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            182 non-null    object
 1   start_of_month  182 non-null    object
 2   month_name      182 non-null    object
 3   day_type        182 non-null    object
dtypes: object(4)
memory usage: 5.8+ KB

In [14]:
#Changing the datatypes of date and start_of_the_month column to Datetime type
dim_date['date'] = pd.to_datetime(dim_date['date'])
dim_date['start_of_month'] = pd.to_datetime(dim_date['start_of_month'])

In [15]:
dim_date.isnull().sum() #no nulls found

date              0
start_of_month    0
month_name        0
day_type          0
dtype: int64

In [16]:
dim_city.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   city_id    10 non-null     object
 1   city_name  10 non-null     object
dtypes: object(2)
memory usage: 288.0+ bytes

In [17]:
dim_city['city_name'].unique()

array(['Jaipur', 'Lucknow', 'Surat', 'Kochi', 'Indore', 'Chandigarh',
       'Vadodara', 'Visakhapatnam', 'Coimbatore', 'Mysore'], dtype=object)

In [18]:
dim_city.shape

(10, 2)

In [19]:
dim_repeat_trip_distribution.info() #month column is of object type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   month                   540 non-null    object
 1   city_id                 540 non-null    object
 2   trip_count              540 non-null    object
 3   repeat_passenger_count  540 non-null    int64
dtypes: int64(1), object(3)
memory usage: 17.0+ KB

In [20]:
dim_repeat_trip_distribution['month'] = pd.to_datetime(dim_repeat_trip_distribution['month']) #Changing datatype of month column to Datetime type

In [21]:
dim_repeat_trip_distribution.isnull().sum() #no nulls found

month                     0
city_id                   0
trip_count                0
repeat_passenger_count    0
dtype: int64

In [22]:
dim_repeat_trip_distribution.shape #this table has 540 rows and 4 columns

(540, 4)

In [23]:
dim_repeat_trip_distribution.head() #the trip count values are digits-string combination

       month city_id trip_count  repeat_passenger_count
0 2024-01-01    AP01   10-Trips                       7
1 2024-01-01    AP01    2-Trips                     352
2 2024-01-01    AP01    3-Trips                     158
3 2024-01-01    AP01    4-Trips                      53
4 2024-01-01    AP01    5-Trips                      38

In [24]:
dim_repeat_trip_distribution['trip_count_num'] = dim_repeat_trip_distribution['trip_count'].str.extract(r'(\d+)').astype('int') #creating a new column with only numbers from trip_count column

dim_repeat_trip_distribution.head()

       month city_id trip_count  repeat_passenger_count  trip_count_num
0 2024-01-01    AP01   10-Trips                       7              10
1 2024-01-01    AP01    2-Trips                     352               2
2 2024-01-01    AP01    3-Trips                     158               3
3 2024-01-01    AP01    4-Trips                      53               4
4 2024-01-01    AP01    5-Trips                      38               5

In [25]:
fact_passenger_summary.head()

        month city_id  new_passengers  repeat_passengers  total_passengers
0  2024-01-01    AP01            2513                650              3163
1  2024-01-01    CH01            3920                720              4640
2  2024-01-01    GJ01            2432               1184              3616
3  2024-01-01    GJ02            2089                544              2633
4  2024-01-01    KA01            1957                172              2129

In [26]:
fact_passenger_summary.info() #month column is listed as object type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   month              60 non-null     object
 1   city_id            60 non-null     object
 2   new_passengers     60 non-null     int64
 3   repeat_passengers  60 non-null     int64
 4   total_passengers   60 non-null     int64
dtypes: int64(3), object(2)
memory usage: 2.5+ KB

In [27]:
fact_passenger_summary['month'] = pd.to_datetime(fact_passenger_summary['month']) #changing the datatype of month column to Datetime

In [28]:
fact_passenger_summary.describe()

,month,new_passengers,repeat_passengers,total_passengers
count,60,60.000000,60.000000,60.000000
mean,2024-03-16 20:00:00,2949.966667,1021.850000,3971.816667
min,2024-01-01 00:00:00,1039.000000,172.000000,1543.000000
25%,2024-02-01 00:00:00,1844.500000,689.750000,2516.250000
50%,2024-03-16 12:00:00,2212.000000,980.500000,3417.000000
75%,2024-05-01 00:00:00,3287.250000,1491.000000,4675.250000
max,2024-06-01 00:00:00,10789.000000,1853.000000,12450.000000
std,NaN,1960.397676,489.245833,2233.462741

In [29]:
fact_trips.info() #date column is of object type

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 425903 entries, 0 to 425902
Data columns (total 8 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   trip_id                 425903 non-null  object
 1   date                    425903 non-null  object
 2   city_id                 425903 non-null  object
 3   passenger_type          425903 non-null  object
 4   distance_travelled(km)  425903 non-null  int64
 5   fare_amount             425903 non-null  int64
 6   passenger_rating        425903 non-null  int64
 7   driver_rating           425903 non-null  int64
dtypes: int64(4), object(4)
memory usage: 26.0+ MB

In [30]:
fact_trips['date'] = pd.to_datetime(fact_trips['date']) #changing the date column datatype to Datetime

In [31]:
fact_trips.isna().sum() #no nulls found

trip_id                   0
date                      0
city_id                   0
passenger_type            0
distance_travelled(km)    0
fare_amount               0
passenger_rating          0
driver_rating             0
dtype: int64

In [32]:
fact_trips['fare_amount'].describe()

count    425903.000000
mean        254.020495
std         159.638784
min          58.000000
25%         135.000000
50%         199.000000
75%         337.000000
max         802.000000
Name: fare_amount, dtype: float64

In [33]:
avg, std = fact_trips['fare_amount'].mean(), fact_trips['fare_amount'].std()
avg, std

(np.float64(254.0204952770936), np.float64(159.6387842431832))

In [34]:
higher_limit = avg + 3*std
higher_limit

np.float64(732.9368480066432)

In [35]:
fact_trips[fact_trips['fare_amount']>higher_limit] #validating outliers

,trip_id,date,city_id,passenger_type,distance_travelled(km),fare_amount,passenger_rating,driver_rating
23,TRPJAI24012860cb01fe,2024-01-28,RJ01,new,42,751,9,9
57,TRPJAI2405182555b05c,2024-05-18,RJ01,new,44,785,9,8
60,TRPJAI240602746056b9,2024-06-02,RJ01,new,41,734,9,9
123,TRPJAI240622041a25f8,2024-06-22,RJ01,repeated,41,734,7,8
202,TRPJAI240616a459677c,2024-06-16,RJ01,repeated,42,751,7,10
...,...,...,...,...,...,...,...,...
425699,TRPJAI240310b5295a14,2024-03-10,RJ01,repeated,45,802,9,10
425776,TRPJAI240303c410290b,2024-03-03,RJ01,new,45,802,8,10
425818,TRPJAI240608ad867f08,2024-06-08,RJ01,new,41,734,8,10
425833,TRPJAI24042171337423,2024-04-21,RJ01,new,42,751,9,9
425897,TRPJAI240204af6f46f6,2024-02-04,RJ01,new,41,734,10,9

In [36]:
fact_trips.loc[
    fact_trips['fare_amount'] > higher_limit,
    'fare_amount'
].describe()

count    7335.000000
mean      768.185412
std        24.249813
min       734.000000
25%       751.000000
50%       768.000000
75%       785.000000
max       802.000000
Name: fare_amount, dtype: float64

In [37]:
fact_trips.loc[
    fact_trips['fare_amount'] > higher_limit,
    ['trip_id', 'date', 'city_id', 'distance_travelled(km)', 'fare_amount']
].head(20) #most of the trips are more than 40km which leads to high fare amount which is usual. Thus, we cannot remove these 7335 records

,trip_id,date,city_id,distance_travelled(km),fare_amount
23,TRPJAI24012860cb01fe,2024-01-28,RJ01,42,751
57,TRPJAI2405182555b05c,2024-05-18,RJ01,44,785
60,TRPJAI240602746056b9,2024-06-02,RJ01,41,734
123,TRPJAI240622041a25f8,2024-06-22,RJ01,41,734
202,TRPJAI240616a459677c,2024-06-16,RJ01,42,751
280,TRPJAI2402044c3575ed,2024-02-04,RJ01,42,751
345,TRPJAI240323368ebe0c,2024-03-23,RJ01,42,751
376,TRPJAI240602371fabad,2024-06-02,RJ01,44,785
386,TRPJAI240615fbae7f73,2024-06-15,RJ01,45,802
400,TRPJAI2406014926458e,2024-06-01,RJ01,41,734
410,TRPJAI24062288512d10,2024-06-22,RJ01,42,751
432,TRPJAI240106d796fb6c,2024-01-06,RJ01,43,768
563,TRPJAI2404074d6cbf83,2024-04-07,RJ01,43,768
613,TRPJAI2403179685866b,2024-03-17,RJ01,43,768
718,TRPJAI2403176e4e5f2a,2024-03-17,RJ01,44,785
728,TRPJAI240324ee670814,2024-03-24,RJ01,42,751
823,TRPJAI240427674442f3,2024-04-27,RJ01,45,802
897,TRPJAI240127f1000547,2024-01-27,RJ01,41,734
985,TRPJAI2405183f79cf8b,2024-05-18,RJ01,41,734
1058,TRPJAI24060914f5507c,2024-06-09,RJ01,45,802

In [38]:
monthly_target_new_passengers['month'] = pd.to_datetime(monthly_target_new_passengers['month']) #changing month column datatype to Datetime
monthly_target_new_passengers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   month                  60 non-null     datetime64[ns]
 1   city_id                60 non-null     object
 2   target_new_passengers  60 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 1.5+ KB

In [39]:
monthly_target_new_passengers['target_new_passengers'].describe()

count       60.000000
mean      3085.000000
std       2412.104012
min       1000.000000
25%       1950.000000
50%       2000.000000
75%       3400.000000
max      12000.000000
Name: target_new_passengers, dtype: float64

In [40]:
monthly_target_trips.info() #Datatype of month column is object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   month               60 non-null     object
 1   city_id             60 non-null     object
 2   total_target_trips  60 non-null     int64
dtypes: int64(1), object(2)
memory usage: 1.5+ KB

In [41]:
monthly_target_trips['month'] = pd.to_datetime(monthly_target_trips['month']) #changing the datatype of month column to Datetype
monthly_target_trips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   month               60 non-null     datetime64[ns]
 1   city_id             60 non-null     object
 2   total_target_trips  60 non-null     int64
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 1.5+ KB

In [42]:
monthly_target_trips.isnull().sum() #no nulls found

month                 0
city_id               0
total_target_trips    0
dtype: int64

In [43]:
monthly_target_trips.shape

(60, 3)

In [44]:
city_target_passenger_rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   city_id                      10 non-null     object
 1   target_avg_passenger_rating  10 non-null     float64
dtypes: float64(1), object(1)
memory usage: 288.0+ bytes

In [45]:
city_target_passenger_rating.shape

(10, 2)

In [46]:
city_target_passenger_rating.isnull().sum() #no nulls found

city_id                        0
target_avg_passenger_rating    0
dtype: int64

In [47]:
city_target_passenger_rating['city_id'].unique()

array(['CH01', 'UP01', 'AP01', 'MP01', 'RJ01', 'KA01', 'GJ01', 'TN01',
       'KL01', 'GJ02'], dtype=object)

In [48]:
city_target_passenger_rating

  city_id  target_avg_passenger_rating
0    CH01                         8.00
1    UP01                         7.25
2    AP01                         8.50
3    MP01                         8.00
4    RJ01                         8.25
5    KA01                         8.50
6    GJ01                         7.00
7    TN01                         8.25
8    KL01                         8.50
9    GJ02                         7.50

In [49]:
monthly_target_trips.duplicated(
    subset=['month', 'city_id']
).sum()

np.int64(0)

In [50]:
monthly_target_new_passengers.duplicated(
    subset=['month', 'city_id']
).sum()

np.int64(0)

In [51]:
fact_trips.head()

,trip_id,date,city_id,passenger_type,distance_travelled(km),fare_amount,passenger_rating,driver_rating
0,TRPLUC240113d55de2fb,2024-01-13,UP01,repeated,11,158,5,5
1,TRPVAD240129a3b6dba8,2024-01-29,GJ02,repeated,7,74,5,5
2,TRPCOI240107a42430fb,2024-01-07,TN01,repeated,11,155,8,8
3,TRPKOC240325d7601389,2024-03-25,KL01,repeated,36,427,9,10
4,TRPVIS2406027be97166,2024-06-02,AP01,new,17,265,8,8

In [52]:
fact_trips['month'] = fact_trips['date'].dt.to_period('M').dt.to_timestamp() #adding a month column

In [53]:
monthly_city_trips = (fact_trips.groupby(['month', 'city_id']).agg(total_trips = ('trip_id' , 'count'), total_distance_travelled_km = ('distance_travelled(km)','sum'), total_fare = ('fare_amount', 'sum'), avg_passenger_rating = ('passenger_rating', 'mean'), avg_driver_rating = ('driver_rating', 'mean')).reset_index()) #creating a new table by aggregating columns and grouping by city_id and month
monthly_city_trips.head()

,month,city_id,total_trips,total_distance_travelled_km,total_fare,avg_passenger_rating,avg_driver_rating
0,2024-01-01,AP01,4468,101149,1261087,8.553939,8.994628
1,2024-01-01,CH01,6810,160481,1934293,8.068135,7.781057
2,2024-01-01,GJ01,8358,91742,979549,6.577531,6.634841
3,2024-01-01,GJ02,4775,54966,564904,6.850471,6.715602
4,2024-01-01,KA01,2485,40837,613540,8.788732,8.975453

In [54]:
master_table = monthly_city_trips.merge(city_target_passenger_rating, on = 'city_id', how = 'left') #joining targer_avg_passenger_rating column with monthly_city_trips
master_table.head()

,month,city_id,total_trips,total_distance_travelled_km,total_fare,avg_passenger_rating,avg_driver_rating,target_avg_passenger_rating
0,2024-01-01,AP01,4468,101149,1261087,8.553939,8.994628,8.5
1,2024-01-01,CH01,6810,160481,1934293,8.068135,7.781057,8.0
2,2024-01-01,GJ01,8358,91742,979549,6.577531,6.634841,7.0
3,2024-01-01,GJ02,4775,54966,564904,6.850471,6.715602,7.5
4,2024-01-01,KA01,2485,40837,613540,8.788732,8.975453,8.5

In [55]:
#merging fact_passenger_summary type table with master_table
master_table = pd.merge(master_table, fact_passenger_summary, on=['month', 'city_id'])
master_table.head()

,month,city_id,total_trips,total_distance_travelled_km,total_fare,avg_passenger_rating,avg_driver_rating,target_avg_passenger_rating,new_passengers,repeat_passengers,total_passengers
0,2024-01-01,AP01,4468,101149,1261087,8.553939,8.994628,8.5,2513,650,3163
1,2024-01-01,CH01,6810,160481,1934293,8.068135,7.781057,8.0,3920,720,4640
2,2024-01-01,GJ01,8358,91742,979549,6.577531,6.634841,7.0,2432,1184,3616
3,2024-01-01,GJ02,4775,54966,564904,6.850471,6.715602,7.5,2089,544,2633
4,2024-01-01,KA01,2485,40837,613540,8.788732,8.975453,8.5,1957,172,2129

In [56]:
#merging monthly_target_new_passengers table with master_table
master_table = pd.merge(master_table, monthly_target_new_passengers, on= ['month', 'city_id'])
master_table.head()

,month,city_id,total_trips,total_distance_travelled_km,total_fare,avg_passenger_rating,avg_driver_rating,target_avg_passenger_rating,new_passengers,repeat_passengers,total_passengers,target_new_passengers
0,2024-01-01,AP01,4468,101149,1261087,8.553939,8.994628,8.5,2513,650,3163,2500
1,2024-01-01,CH01,6810,160481,1934293,8.068135,7.781057,8.0,3920,720,4640,4000
2,2024-01-01,GJ01,8358,91742,979549,6.577531,6.634841,7.0,2432,1184,3616,2000
3,2024-01-01,GJ02,4775,54966,564904,6.850471,6.715602,7.5,2089,544,2633,1800
4,2024-01-01,KA01,2485,40837,613540,8.788732,8.975453,8.5,1957,172,2129,2000

In [57]:
#Creating a new column to count target vs actual new passengers
master_table['new_passengers_variance'] = master_table['new_passengers'] - master_table['target_new_passengers']

In [58]:
#merging monthly_target_trips table with master_table to have avg_passenger_rating
master_table = pd.merge(master_table, monthly_target_trips, on= ['month','city_id'])

In [59]:
#Creating a new column trips_variance to count target vs actual trips
master_table['trips_variance'] = master_table['total_trips'] - master_table['total_target_trips']

In [60]:
master_table.head()

,month,city_id,total_trips,total_distance_travelled_km,total_fare,avg_passenger_rating,avg_driver_rating,target_avg_passenger_rating,new_passengers,repeat_passengers,total_passengers,target_new_passengers,new_passengers_variance,total_target_trips,trips_variance
0,2024-01-01,AP01,4468,101149,1261087,8.553939,8.994628,8.5,2513,650,3163,2500,13,4500,-32
1,2024-01-01,CH01,6810,160481,1934293,8.068135,7.781057,8.0,3920,720,4640,4000,-80,7000,-190
2,2024-01-01,GJ01,8358,91742,979549,6.577531,6.634841,7.0,2432,1184,3616,2000,432,9000,-642
3,2024-01-01,GJ02,4775,54966,564904,6.850471,6.715602,7.5,2089,544,2633,1800,289,6000,-1225
4,2024-01-01,KA01,2485,40837,613540,8.788732,8.975453,8.5,1957,172,2129,2000,-43,2000,485

In [61]:
print(monthly_city_trips.shape)
print(monthly_city_trips.isna().sum())

(60, 7)
month                          0
city_id                        0
total_trips                    0
total_distance_travelled_km    0
total_fare                     0
avg_passenger_rating           0
avg_driver_rating              0
dtype: int64

In [62]:
#Creating new column to count new and repeat passenger percentages
master_table['new_passenger_pct'] = master_table['new_passengers'] / master_table['total_passengers'] * 100
master_table['repeat_passenger_pct'] = master_table['repeat_passengers'] / master_table['total_passengers'] * 100

In [63]:
#Rounding these newly created columns to two decimal numbers
master_table['new_passenger_pct'] = master_table['new_passenger_pct'].round(2)
master_table['repeat_passenger_pct'] = master_table['repeat_passenger_pct'].round(2)

In [64]:
#Creating new columns to calculate percentages of new passenger variance and trip variance
master_table['new_pass_var_pct'] = master_table['new_passengers_variance'] / master_table['target_new_passengers'] * 100

In [65]:
master_table['trips_var_pct'] = master_table['trips_variance'] / master_table['total_target_trips'] * 100

In [67]:
#Rounding these newly created columns to two decimal numbers
master_table['new_pass_var_pct'] = master_table['new_pass_var_pct'].round(2)
master_table['trips_var_pct'] = master_table['trips_var_pct'].round(2)

In [70]:
#Final Master Table
master_table.head()

,month,city_id,total_trips,total_distance_travelled_km,total_fare,avg_passenger_rating,avg_driver_rating,target_avg_passenger_rating,new_passengers,repeat_passengers,total_passengers,target_new_passengers,new_passengers_variance,total_target_trips,trips_variance,new_passenger_pct,repeat_passenger_pct,new_pass_var_pct,trips_var_pct
0,2024-01-01,AP01,4468,101149,1261087,8.553939,8.994628,8.5,2513,650,3163,2500,13,4500,-32,79.45,20.55,0.52,-0.71
1,2024-01-01,CH01,6810,160481,1934293,8.068135,7.781057,8.0,3920,720,4640,4000,-80,7000,-190,84.48,15.52,-2.00,-2.71
2,2024-01-01,GJ01,8358,91742,979549,6.577531,6.634841,7.0,2432,1184,3616,2000,432,9000,-642,67.26,32.74,21.60,-7.13
3,2024-01-01,GJ02,4775,54966,564904,6.850471,6.715602,7.5,2089,544,2633,1800,289,6000,-1225,79.34,20.66,16.06,-20.42
4,2024-01-01,KA01,2485,40837,613540,8.788732,8.975453,8.5,1957,172,2129,2000,-43,2000,485,91.92,8.08,-2.15,24.25

In [76]:
#Exporting the dimensions, facts, targets and master tables into BigQuery for further analysis

#dimenstion tables
dim_city.to_csv('dim_city_clean.csv', index = False)
dim_date.to_csv('dim_date_clean.csv', index = False)
dim_repeat_trip_distribution.to_csv('dim_repeat_trip_distribution_clean.csv', index = False)

#Fact Tables
fact_passenger_summary.to_csv('fact_passenger_summary_clean.csv', index = False)
fact_trips.to_csv('fact_trips_clean.csv', index = False)

#Target Tables
city_target_passenger_rating.to_csv('city_target_passenger_rating_clean.csv', index = False)
monthly_target_new_passengers.to_csv('monthly_target_new_passengers_clean.csv', index = False)
monthly_target_trips.to_csv('monthly_target_trips_clean.csv', index = False)

#Master Table
master_table.to_csv('master_table.csv', index = False)